In [3]:
import numpy as np

In [4]:
a = [[1,2,3],[1,3,2]]

In [5]:
b = numpy.array(a)

In [6]:
b

array([[1, 2, 3],
       [1, 3, 2]])

In [7]:
a[0] == a[1]

False

In [8]:
b

array([[1, 2, 3],
       [1, 3, 2]])

In [19]:
for i in range(3):
    print(i)

0
1
2


In [13]:
b

array([[1, 2, 3],
       [1, 3, 2]])

In [14]:
a={}

In [16]:
a['a'] =[1,2]

In [17]:
a['a']

[1, 2]