In [3]:
import numpy as np

In [4]:
a = [[1,2,3],[1,3,2]]

In [5]:
b = numpy.array(a)

In [6]:
b

array([[1, 2, 3],
       [1, 3, 2]])

In [7]:
a[0] == a[1]

False

In [8]:
b

array([[1, 2, 3],
       [1, 3, 2]])

In [19]:
for i in range(3):
    print(i)

0
1
2


In [13]:
b

array([[1, 2, 3],
       [1, 3, 2]])

In [14]:
a={}

In [16]:
a['a'] =[1,2]

In [17]:
a['a']

[1, 2]

In [1]:
for i in range(2):
    print(i)

0
1


In [10]:
a = [[(1,2),(2,3),(3,4),(4,5),(1,1)],[(1,2)],[(1,1)]]
b = a[0]

for i in range(len(a)-1):
    b = [x for x in b if x not in a[i+1]]

b

[(2, 3), (3, 4), (4, 5)]

In [5]:
from scipy.stats import nakagami 
import numpy as np  
numargs = nakagami.numargs  
a, b = 4.32, 3.18
rv = nakagami(a, b)  
    
print ("RV : \n", rv)
quantile = np.arange (0.01, 1, 0.1)  
  
# Random Variates  
R = nakagami.rvs(a, b)  
print ("Random Variates : \n", R)  
  
# PDF  
R = nakagami.pdf(a, b, quantile)  
print ("\nProbability Distribution : \n", R)  

RV : 
Random Variates : 
 4.340118317219206

Probability Distribution : 
 [1.85789479e-21 2.46056635e-20 3.04869642e-19 3.53340722e-18
 3.83004595e-17 3.88212947e-16 3.67883876e-15 3.25865605e-14
 2.69748016e-13 2.08625145e-12]


In [61]:
from scipy.stats import nakagami 
import numpy as np  
numargs = nakagami.numargs  
a, b = 4.32, 3.18    

  
# Random Variates  
R = nakagami.rvs(a, b)  
print ("Random Variates : \n", R)  
  


Random Variates : 
 3.7292877970099916


In [52]:
import numpy
a=numpy.random.randn(1)
print(a)

[0.46963694]


In [62]:
a = [1,2,3]
b=tuple(a)
b

(1, 2, 3)

In [3]:
import numpy
a=[1+1j,2+2j]
numpy.rad2deg(numpy.arctan(1))

45.0