In [3]:
import numpy as np

In [4]:
a = [[1,2,3],[1,3,2]]

In [5]:
b = numpy.array(a)

In [6]:
b

array([[1, 2, 3],
       [1, 3, 2]])

In [7]:
a[0] == a[1]

False

In [8]:
b

array([[1, 2, 3],
       [1, 3, 2]])

In [19]:
for i in range(3):
    print(i)

0
1
2


In [13]:
b

array([[1, 2, 3],
       [1, 3, 2]])

In [14]:
a={}

In [16]:
a['a'] =[1,2]

In [17]:
a['a']

[1, 2]

In [1]:
for i in range(2):
    print(i)

0
1


In [10]:
a = [[(1,2),(2,3),(3,4),(4,5),(1,1)],[(1,2)],[(1,1)]]
b = a[0]

for i in range(len(a)-1):
    b = [x for x in b if x not in a[i+1]]

b

[(2, 3), (3, 4), (4, 5)]

In [5]:
from scipy.stats import nakagami 
import numpy as np  
numargs = nakagami.numargs  
a, b = 4.32, 3.18
rv = nakagami(a, b)  
    
print ("RV : \n", rv)
quantile = np.arange (0.01, 1, 0.1)  
  
# Random Variates  
R = nakagami.rvs(a, b)  
print ("Random Variates : \n", R)  
  
# PDF  
R = nakagami.pdf(a, b, quantile)  
print ("\nProbability Distribution : \n", R)  

RV : 
Random Variates : 
 4.340118317219206

Probability Distribution : 
 [1.85789479e-21 2.46056635e-20 3.04869642e-19 3.53340722e-18
 3.83004595e-17 3.88212947e-16 3.67883876e-15 3.25865605e-14
 2.69748016e-13 2.08625145e-12]


In [61]:
from scipy.stats import nakagami 
import numpy as np  
numargs = nakagami.numargs  
a, b = 4.32, 3.18    

  
# Random Variates  
R = nakagami.rvs(a, b)  
print ("Random Variates : \n", R)  
  


Random Variates : 
 3.7292877970099916


In [52]:
import numpy
a=numpy.random.randn(1)
print(a)

[0.46963694]


In [62]:
a = [1,2,3]
b=tuple(a)
b

(1, 2, 3)

In [3]:
import numpy
a=[1+1j,2+2j]
numpy.rad2deg(numpy.arctan(1))

45.0

In [10]:
a = {(1,2,3): (1,2),(1,2,4):(2,2)}
a[(1,2,3)]

(1, 2)

In [3]:
import time
a = time.time()
print(str(a))

1587169248.3801963


In [13]:
a = [1,2,3]
a.pop(str(x for x in [0,2]))

TypeError: 'str' object cannot be interpreted as an integer

In [9]:
a

[1, 3]

In [17]:
a = [1,2,3]
a= list(reversed(a))
a

[3, 2, 1]

In [2]:
a = (1,2,3)
a = tuple(reversed(a))
a

(3, 2, 1)

In [7]:
import numpy
a = numpy.ones((30,10))
for i in range((a.shape[0])):
    for j in range(a.shape[1]):
        if a[i,j] == 1:
            a[i+1,j] =1
            a[i,j+1] =1
            a

0 0
0 1
0 2
0 3
0 4
0 5
0 6
0 7
0 8
0 9
1 0
1 1
1 2
1 3
1 4
1 5
1 6
1 7
1 8
1 9
2 0
2 1
2 2
2 3
2 4
2 5
2 6
2 7
2 8
2 9
3 0
3 1
3 2
3 3
3 4
3 5
3 6
3 7
3 8
3 9
4 0
4 1
4 2
4 3
4 4
4 5
4 6
4 7
4 8
4 9
5 0
5 1
5 2
5 3
5 4
5 5
5 6
5 7
5 8
5 9
6 0
6 1
6 2
6 3
6 4
6 5
6 6
6 7
6 8
6 9
7 0
7 1
7 2
7 3
7 4
7 5
7 6
7 7
7 8
7 9
8 0
8 1
8 2
8 3
8 4
8 5
8 6
8 7
8 8
8 9
9 0
9 1
9 2
9 3
9 4
9 5
9 6
9 7
9 8
9 9
10 0
10 1
10 2
10 3
10 4
10 5
10 6
10 7
10 8
10 9
11 0
11 1
11 2
11 3
11 4
11 5
11 6
11 7
11 8
11 9
12 0
12 1
12 2
12 3
12 4
12 5
12 6
12 7
12 8
12 9
13 0
13 1
13 2
13 3
13 4
13 5
13 6
13 7
13 8
13 9
14 0
14 1
14 2
14 3
14 4
14 5
14 6
14 7
14 8
14 9
15 0
15 1
15 2
15 3
15 4
15 5
15 6
15 7
15 8
15 9
16 0
16 1
16 2
16 3
16 4
16 5
16 6
16 7
16 8
16 9
17 0
17 1
17 2
17 3
17 4
17 5
17 6
17 7
17 8
17 9
18 0
18 1
18 2
18 3
18 4
18 5
18 6
18 7
18 8
18 9
19 0
19 1
19 2
19 3
19 4
19 5
19 6
19 7
19 8
19 9
20 0
20 1
20 2
20 3
20 4
20 5
20 6
20 7
20 8
20 9
21 0
21 1
21 2
21 3
21 4
21 5
21 6
21 7
21 8
21 9


In [8]:
import numpy
a=numpy.arctan2(0,0.5)
a

0.0

In [1]:
a = [14, 140]

In [1]:
for i in range(3,11,1):
    print(i)

3
4
5
6
7
8
9
10
